# Generated by Django 2.2 on 2019-05-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileuser',
            name='daily_milk_production',
        ),
        migrations.RemoveField(
            model_name='mobileuser',
            name='milk_type',
        ),
        migrations.RemoveField(
            model_name='mobileuser',
            name='number_animals',
        ),
    ]
