# Generated by Django 2.2 on 2019-05-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190501_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='daily_milk_production',
            field=models.IntegerField(default=0),
        ),
    ]
