# Generated by Django 2.2.1 on 2019-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190509_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='otp_count',
            field=models.IntegerField(default=0),
        ),
    ]
