# Generated by Django 2.2.1 on 2019-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190518_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='mobile_info',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='otp_count',
            field=models.IntegerField(default=1),
        ),
    ]
